// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch-daemon/pkg/ecc (interfaces: ExecCmd)
//
// Generated by this command:
//
//	mockgen --destination=../../mocks/mocks_ecc/execcmd.go -package=mocks_ecc github.com/runfinch/finch-daemon/pkg/ecc ExecCmd
//

// Package mocks_ecc is a generated GoMock package.
package mocks_ecc

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExecCmd is a mock of ExecCmd interface.
type MockExecCmd struct {
	ctrl     *gomock.Controller
	recorder *MockExecCmdMockRecorder
	isgomock struct{}
}

// MockExecCmdMockRecorder is the mock recorder for MockExecCmd.
type MockExecCmdMockRecorder struct {
	mock *MockExecCmd
}

// NewMockExecCmd creates a new mock instance.
func NewMockExecCmd(ctrl *gomock.Controller) *MockExecCmd {
	mock := &MockExecCmd{ctrl: ctrl}
	mock.recorder = &MockExecCmdMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecCmd) EXPECT() *MockExecCmdMockRecorder {
	return m.recorder
}

// GetDir mocks base method.
func (m *MockExecCmd) GetDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDir indicates an expected call of GetDir.
func (mr *MockExecCmdMockRecorder) GetDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDir", reflect.TypeOf((*MockExecCmd)(nil).GetDir))
}

// Run mocks base method.
func (m *MockExecCmd) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockExecCmdMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockExecCmd)(nil).Run))
}

// SetDir mocks base method.
func (m *MockExecCmd) SetDir(path string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDir", path)
}

// SetDir indicates an expected call of SetDir.
func (mr *MockExecCmdMockRecorder) SetDir(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDir", reflect.TypeOf((*MockExecCmd)(nil).SetDir), path)
}

// SetStderr mocks base method.
func (m *MockExecCmd) SetStderr(writer io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStderr", writer)
}

// SetStderr indicates an expected call of SetStderr.
func (mr *MockExecCmdMockRecorder) SetStderr(writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStderr", reflect.TypeOf((*MockExecCmd)(nil).SetStderr), writer)
}

// SetStdin mocks base method.
func (m *MockExecCmd) SetStdin(reader io.Reader) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdin", reader)
}

// SetStdin indicates an expected call of SetStdin.
func (mr *MockExecCmdMockRecorder) SetStdin(reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdin", reflect.TypeOf((*MockExecCmd)(nil).SetStdin), reader)
}

// SetStdout mocks base method.
func (m *MockExecCmd) SetStdout(writer io.Writer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStdout", writer)
}

// SetStdout indicates an expected call of SetStdout.
func (mr *MockExecCmdMockRecorder) SetStdout(writer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStdout", reflect.TypeOf((*MockExecCmd)(nil).SetStdout), writer)
}
