// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch-daemon/pkg/archive (interfaces: TarExtractor)
//
// Generated by this command:
//
//	mockgen --destination=../../mocks/mocks_archive/tarextractor.go -package=mocks_archive github.com/runfinch/finch-daemon/pkg/archive TarExtractor
//

// Package mocks_archive is a generated GoMock package.
package mocks_archive

import (
	io "io"
	reflect "reflect"

	archive "github.com/moby/go-archive"
	ecc "github.com/runfinch/finch-daemon/pkg/ecc"
	gomock "go.uber.org/mock/gomock"
)

// MockTarExtractor is a mock of TarExtractor interface.
type MockTarExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockTarExtractorMockRecorder
	isgomock struct{}
}

// MockTarExtractorMockRecorder is the mock recorder for MockTarExtractor.
type MockTarExtractorMockRecorder struct {
	mock *MockTarExtractor
}

// NewMockTarExtractor creates a new mock instance.
func NewMockTarExtractor(ctrl *gomock.Controller) *MockTarExtractor {
	mock := &MockTarExtractor{ctrl: ctrl}
	mock.recorder = &MockTarExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTarExtractor) EXPECT() *MockTarExtractorMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockTarExtractor) Cleanup(cmd ecc.ExecCmd) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup", cmd)
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockTarExtractorMockRecorder) Cleanup(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockTarExtractor)(nil).Cleanup), cmd)
}

// CreateExtractCmd mocks base method.
func (m *MockTarExtractor) CreateExtractCmd(reader io.Reader, destDir string) (ecc.ExecCmd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExtractCmd", reader, destDir)
	ret0, _ := ret[0].(ecc.ExecCmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExtractCmd indicates an expected call of CreateExtractCmd.
func (mr *MockTarExtractorMockRecorder) CreateExtractCmd(reader, destDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExtractCmd", reflect.TypeOf((*MockTarExtractor)(nil).CreateExtractCmd), reader, destDir)
}

// ExtractCompressed mocks base method.
func (m *MockTarExtractor) ExtractCompressed(tarArchive io.Reader, dest string, options *archive.TarOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractCompressed", tarArchive, dest, options)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExtractCompressed indicates an expected call of ExtractCompressed.
func (mr *MockTarExtractorMockRecorder) ExtractCompressed(tarArchive, dest, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractCompressed", reflect.TypeOf((*MockTarExtractor)(nil).ExtractCompressed), tarArchive, dest, options)
}

// ExtractInTemp mocks base method.
func (m *MockTarExtractor) ExtractInTemp(reader io.Reader, dirPrefix string) (ecc.ExecCmd, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractInTemp", reader, dirPrefix)
	ret0, _ := ret[0].(ecc.ExecCmd)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractInTemp indicates an expected call of ExtractInTemp.
func (mr *MockTarExtractorMockRecorder) ExtractInTemp(reader, dirPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractInTemp", reflect.TypeOf((*MockTarExtractor)(nil).ExtractInTemp), reader, dirPrefix)
}
