// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch-daemon/internal/backend (interfaces: ContainerCNISvc)
//
// Generated by this command:
//
//	mockgen --destination=../../mocks/mocks_backend/containercnisvc.go -package=mocks_backend github.com/runfinch/finch-daemon/internal/backend ContainerCNISvc

// Package mocks_backend is a generated GoMock package.
package mocks_backend

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockContainerCNISvc is a mock of ContainerCNISvc interface.
type MockContainerCNISvc struct {
	ctrl     *gomock.Controller
	recorder *MockContainerCNISvcMockRecorder
}

// MockContainerCNISvcMockRecorder is the mock recorder for MockContainerCNISvc.
type MockContainerCNISvcMockRecorder struct {
	mock *MockContainerCNISvc
}

// NewMockContainerCNISvc creates a new mock instance.
func NewMockContainerCNISvc(ctrl *gomock.Controller) *MockContainerCNISvc {
	mock := &MockContainerCNISvc{ctrl: ctrl}
	mock.recorder = &MockContainerCNISvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerCNISvc) EXPECT() *MockContainerCNISvcMockRecorder {
	return m.recorder
}

// RemoveContainerNetwork mocks base method.
func (m *MockContainerCNISvc) RemoveContainerNetwork(ctx context.Context, containerID, networkName, netnsPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveContainerNetwork", ctx, containerID, networkName, netnsPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveContainerNetwork indicates an expected call of RemoveContainerNetwork.
func (mr *MockContainerCNISvcMockRecorder) RemoveContainerNetwork(ctx, containerID, networkName, netnsPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveContainerNetwork", reflect.TypeOf((*MockContainerCNISvc)(nil).RemoveContainerNetwork), ctx, containerID, networkName, netnsPath)
}

// SetupContainerNetwork mocks base method.
func (m *MockContainerCNISvc) SetupContainerNetwork(ctx context.Context, containerID, networkName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetupContainerNetwork", ctx, containerID, networkName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetupContainerNetwork indicates an expected call of SetupContainerNetwork.
func (mr *MockContainerCNISvcMockRecorder) SetupContainerNetwork(ctx, containerID, networkName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetupContainerNetwork", reflect.TypeOf((*MockContainerCNISvc)(nil).SetupContainerNetwork), ctx, containerID, networkName)
}
