// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/runfinch/finch-daemon/internal/backend (interfaces: NerdctlVolumeSvc)

// Package mocks_backend is a generated GoMock package.
package mocks_backend

import (
	context "context"
	io "io"
	reflect "reflect"

	native "github.com/containerd/nerdctl/v2/pkg/inspecttypes/native"
	gomock "github.com/golang/mock/gomock"
)

// MockNerdctlVolumeSvc is a mock of NerdctlVolumeSvc interface.
type MockNerdctlVolumeSvc struct {
	ctrl     *gomock.Controller
	recorder *MockNerdctlVolumeSvcMockRecorder
}

// MockNerdctlVolumeSvcMockRecorder is the mock recorder for MockNerdctlVolumeSvc.
type MockNerdctlVolumeSvcMockRecorder struct {
	mock *MockNerdctlVolumeSvc
}

// NewMockNerdctlVolumeSvc creates a new mock instance.
func NewMockNerdctlVolumeSvc(ctrl *gomock.Controller) *MockNerdctlVolumeSvc {
	mock := &MockNerdctlVolumeSvc{ctrl: ctrl}
	mock.recorder = &MockNerdctlVolumeSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNerdctlVolumeSvc) EXPECT() *MockNerdctlVolumeSvcMockRecorder {
	return m.recorder
}

// CreateVolume mocks base method.
func (m *MockNerdctlVolumeSvc) CreateVolume(arg0 string, arg1 []string) (*native.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVolume", arg0, arg1)
	ret0, _ := ret[0].(*native.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVolume indicates an expected call of CreateVolume.
func (mr *MockNerdctlVolumeSvcMockRecorder) CreateVolume(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVolume", reflect.TypeOf((*MockNerdctlVolumeSvc)(nil).CreateVolume), arg0, arg1)
}

// GetVolume mocks base method.
func (m *MockNerdctlVolumeSvc) GetVolume(arg0 string) (*native.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVolume", arg0)
	ret0, _ := ret[0].(*native.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVolume indicates an expected call of GetVolume.
func (mr *MockNerdctlVolumeSvcMockRecorder) GetVolume(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVolume", reflect.TypeOf((*MockNerdctlVolumeSvc)(nil).GetVolume), arg0)
}

// ListVolumes mocks base method.
func (m *MockNerdctlVolumeSvc) ListVolumes(arg0 bool, arg1 []string) (map[string]native.Volume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVolumes", arg0, arg1)
	ret0, _ := ret[0].(map[string]native.Volume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVolumes indicates an expected call of ListVolumes.
func (mr *MockNerdctlVolumeSvcMockRecorder) ListVolumes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVolumes", reflect.TypeOf((*MockNerdctlVolumeSvc)(nil).ListVolumes), arg0, arg1)
}

// RemoveVolume mocks base method.
func (m *MockNerdctlVolumeSvc) RemoveVolume(arg0 context.Context, arg1 string, arg2 bool, arg3 io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveVolume", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveVolume indicates an expected call of RemoveVolume.
func (mr *MockNerdctlVolumeSvcMockRecorder) RemoveVolume(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveVolume", reflect.TypeOf((*MockNerdctlVolumeSvc)(nil).RemoveVolume), arg0, arg1, arg2, arg3)
}
