name: "Lint PR Title"
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
permissions:
  pull-requests: read
  contents: read

jobs:
  main:
    name: conventional-commit
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        with:
          # List from https://github.com/commitizen/conventional-commit-types/blob/master/index.json
          # with custom types added at the end.
          # Custom types should also be added in release-please.yaml changelog-types.
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
            exp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
