name: samcli-pr-validation

# on:
#   pull_request:
#     branches:
#       - main
#     paths:
#       - '**.go'
#       - 'go.mod'
#       - 'go.sum'
#       - '.github/workflows/samcli_on_pr.yaml'
#       - 'Makefile*'
#       - 'cmd/**'
#       - 'pkg/**'
#       - 'internal/**'
#       - 'api/**'
#   workflow_dispatch:

env:
  GO_VERSION: '1.23.8'
  CONTAINERD_VERSION: "1.7.27"

permissions:
  id-token: write
  contents: read

jobs:
  samcli-minimal-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Much shorter than full suite
    env:
      AWS_DEFAULT_REGION: ${{ secrets.REGION }}
      DOCKER_HOST: unix:///run/finch.sock
      BY_CANARY: true
      SAM_CLI_DEV: 1
      SAM_CLI_TELEMETRY: 0
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          role-to-assume: ${{ secrets.ROLE }}
          role-session-name: samcli-pr-validation
          aws-region: ${{ secrets.REGION }}
          role-duration-seconds: 3600  # Shorter duration for PR tests

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.12'

      - name: Checkout finch-daemon repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Stop pre-existing services
        run: |
          sudo systemctl stop docker
          sudo systemctl stop containerd

      - name: Remove default podman network config
        run: |
          sudo rm -f /etc/cni/net.d/87-podman-bridge.conflist

      - name: Clean up Daemon socket
        run: |
          sudo rm -f /run/finch.sock
          sudo rm -f /run/finch.pid
          sudo rm -f /run/finch-credential.sock

      - name: Install finch-daemon dependencies
        run: |
          ./setup-test-env.sh
          sleep 10

      - name: Build and start finch-daemon
        run: |
          make build
          sudo bin/finch-daemon --debug --socket-owner $UID 2>&1 | tee finch-daemon.log &
          sleep 10

      - name: Set up SAM CLI from source
        run: |
          git clone https://github.com/aws/aws-sam-cli.git
          cd aws-sam-cli
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)  # Latest tag
          git submodule update --init --recursive
          python -m pip install --upgrade pip
          make init
          samdev --version

      - name: Run minimal SAM CLI integration tests
        working-directory: aws-sam-cli
        timeout-minutes: 20
        run: |
          echo "=== MINIMAL SAM CLI TESTS - Started at $(date) ==="
          echo "Testing core Docker API compatibility with finch-daemon"
          
          # Set ulimit for file handles
          ulimit -n 65536
          
          # Use robust test patterns that should work across SAM CLI versions
          echo "Running Test 1: Basic invoke functionality"
          python -m pytest tests/integration/local/invoke/test_integrations_cli.py -k "test_invoke_returncode_is_zero" --tb=short -v --maxfail=1 || TEST1_FAILED=1
          
          echo "Running Test 2: Start-lambda service"
          python -m pytest tests/integration/local/start_lambda/test_start_lambda.py -k "TestLambdaService" --tb=short -v --maxfail=1 || TEST2_FAILED=1
          
          echo "Running Test 3: Basic start-api functionality"
          python -m pytest tests/integration/local/start_api/test_start_api.py -k "test_calling_proxy_endpoint" --tb=short -v --maxfail=1 || TEST3_FAILED=1
          
          # Check results
          if [[ -n "$TEST1_FAILED" || -n "$TEST2_FAILED" || -n "$TEST3_FAILED" ]]; then
            echo "❌ Some minimal tests failed - finch-daemon Docker API compatibility issue detected"
            
            echo ""
            echo "=== FINCH-DAEMON LOGS ==="
            tail -50 ../finch-daemon.log
            
            exit 1
          else
            echo "✅ All minimal tests passed - finch-daemon Docker API compatibility confirmed"
          fi

      - name: Show finch-daemon logs
        if: always()
        run: |
          echo "=== FINCH-DAEMON LOGS ==="
          cat finch-daemon.log || echo "No log file found"

      - name: Cleanup test resources
        if: always()
        timeout-minutes: 5
        run: |
          echo "=== Cleaning up test resources ==="
          
          # Set error handling to continue on failures
          set +e
          
          # Clean up any test stacks that might have been created
          TEST_STACKS=$(aws cloudformation list-stacks --region $AWS_DEFAULT_REGION --stack-status-filter CREATE_COMPLETE UPDATE_COMPLETE --query "StackSummaries[?contains(StackName, 'sam-app') || contains(StackName, 'test-')].[StackName]" --output text 2>/dev/null || true)
          
          if [ -n "$TEST_STACKS" ]; then
            for stack in $TEST_STACKS; do
              echo "Cleaning up test stack: $stack"
              aws cloudformation delete-stack --stack-name "$stack" --region $AWS_DEFAULT_REGION || true
            done
          fi
          
          # Clean up any test Lambda functions
          TEST_FUNCTIONS=$(aws lambda list-functions --region $AWS_DEFAULT_REGION --query "Functions[?contains(FunctionName, 'HelloWorld') || contains(FunctionName, 'test-')].FunctionName" --output text 2>/dev/null || true)
          
          if [ -n "$TEST_FUNCTIONS" ]; then
            for func in $TEST_FUNCTIONS; do
              echo "Cleaning up test function: $func"
              aws lambda delete-function --function-name "$func" --region $AWS_DEFAULT_REGION || true
            done
          fi
          
          echo "✅ Cleanup completed"
